### ISSUE TITLE
Post Auth Feature Request

### ISSUE THREAD

**Issue by Bandisa** [COS301-SE-2023/Pronto#243]
# Feature Request
- [ ] enroll a student to an institution once signed up
- [ ] enroll a lecturer to an institution once they sign up
- [ ] transfer institution ownership to admin once they login
# Components
## backend
- modify post auth to perform the task
## frontend
- after signUp, show a pop up alerting the user, and give them the option to accept/change/skip automatic enrolment popUp
# Justification
We can initiate all of these operations on the client side, but given that the institution is already chosen at sign up, make sense to automate it on the cloud, in addition to provide a client side mechanism.
# Milestone
Demo 4

**Comment by Bandisa** [comment]
This has to be implemented soon, no longer just a request.
