### ISSUE TITLE
Demo 4 documentation checklist

### ISSUE THREAD

**Issue by Tymac15** [COS301-SE-2023/Pronto#299]
- [x] Final SRS
- [x] Final architecture requirement
- [x] Final user manual
- [x] Final technical installation
- [x] Code quality standards
- [x] Quality assurance metrics
- [x] Mobile help pages (navigation screen)
- [x] Lecturer help pages
- [x] Institution help pages
- [x] Update readme

**Comment by Tymac15** [comment]
Completed all the documentation
