### ISSUE TITLE
BETA RELEASE E2E

### ISSUE THREAD

**Issue by Bandisa** [COS301-SE-2023/Pronto#413]
# Tasks
- [x] perform e2e tests on the entire code base and beta backend env
- [ ] deploy to prod through CI/CD pipeline
- [ ] obtain build status for full code base
- [ ] fix bugs

**Comment by Bandisa** [comment]
Some e2e tests were perfomed yesterday, bugs reported, but due to backend folder structure being a mess, caused by my lack of frequent PRs, means that it was hard to merge. Will open the appropiate PRs today.
